// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACLQzclQUqbbOSw9iZvhWSiSbPJBcNueg',
    appId: '1:586039017466:web:f33bf8dd6a2b6e15b2ae43',
    messagingSenderId: '586039017466',
    projectId: 'cryptofunding-55ecd',
    authDomain: 'cryptofunding-55ecd.firebaseapp.com',
    storageBucket: 'cryptofunding-55ecd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMEeoNsZGBGIgQWSZ29OYzWLxY477x1Tc',
    appId: '1:586039017466:android:05875a3091e6eab2b2ae43',
    messagingSenderId: '586039017466',
    projectId: 'cryptofunding-55ecd',
    storageBucket: 'cryptofunding-55ecd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9JEMQLhQ4UicMo7nOPhYSJJWPSK2LGcg',
    appId: '1:586039017466:ios:7b123d649087c158b2ae43',
    messagingSenderId: '586039017466',
    projectId: 'cryptofunding-55ecd',
    storageBucket: 'cryptofunding-55ecd.appspot.com',
    iosClientId: '586039017466-26jfnvqpol3j33snabroid184r6pdtfc.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptoFundingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9JEMQLhQ4UicMo7nOPhYSJJWPSK2LGcg',
    appId: '1:586039017466:ios:7b123d649087c158b2ae43',
    messagingSenderId: '586039017466',
    projectId: 'cryptofunding-55ecd',
    storageBucket: 'cryptofunding-55ecd.appspot.com',
    iosClientId: '586039017466-26jfnvqpol3j33snabroid184r6pdtfc.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptoFundingApp',
  );
}
